- sdp/inside_sdp_image.groovy
Merge into master for updated config to handle docker networking et al
> Update inside sdp image config

- .gitignore
- docker/README.rst
- docker/get_images_to_build.groovy
- docker/get_repo_info.groovy
- docker/login_to_registry.groovy
moved application images to libraries.docker.(registry|cred)
> Library docker images

- docker/build.groovy
- docker/get_images_to_build.groovy
- docker/get_registry_info.groovy
- docker/login_to_registry.groovy
- docker/retag.groovy
- docker/unit-tests/BuildSpec.groovy
- docker/unit-tests/GetImagesToBuildSpec.groovy
- docker/unit-tests/GetRegistryInfoSpec.groovy
- docker/unit-tests/LoginToRegistrySpec.groovy
- docker/unit-tests/RetagSpec.groovy
* revising variable names in the Docker library for clarity (i.e. repository -> registry)
* fixing Docker library unit tests to cover these and other recent changes
> docker library revisions

- docker/README.rst
- sdp/README.rst
Add README for the SDP Library
Self-describing update to the docs.
Proofread and previewed in GitHub.
> Sdp lib readme

- openshift/unit-tests/DeployToSpec.groovy
- pom.xml
- sdp/unit-tests/InsideSdpImageSpec.groovy
Added unit tests for the SDP library
Added 10 unit tests for the inside_sdp_image step of the SDP library
Unit tests pass. For a subset of the tests, the variables have been tinkered with to ensure
the tests pass/fail as expected.
> Sdp lib tests

- github_enterprise/on_merge.groovy
> Use GIT_URL env var instead of `git remote -v`

- github/README.rst
- github/git.groovy
- github/github_enterprise_constructor.groovy
- github/on_change.groovy
- github/on_commit.groovy
- github/on_merge.groovy
- github/on_pull_request.groovy
- github/withGit.groovy
pipeline-config: cokieffebah/sdp-ex-libraries:{ branch:master, configBaseDir:github-library}
scm:github: boozallen/sdp-labs-sample-app:{ branch:github-library }
did a PR, for basic github, boozallen/sdp-labs-sample-app/pull/2, to: github-library, from: github-lib-pr
did a PR, for github enterprise, https://github.boozallencsn.com/O-Kieffe-Carlos/sdp-labs-sample-app/pull/1, using copies of the above branches from boozallen/sdp-labs-sample-app
> GitHub from enterprise

- docker/README.rst
Some of the Docker library's documentation was out of date. This PR should fix that.
> updating Docker library documentation

- github/library_config.groovy
Added a library config file for the GitHub Library
The library config specifies one required field, source_type, which must be either 'github' or 'github_enterprise'
The github library with these changes was loaded in a simple pipeline
> GitHub library config

- sonarqube/library_config.groovy
Added a library config file for the Sonarqube library
Specified 2 optional fields in the library config file for the Sonarqube library:
* credential_id can only contain certain characters (per Credentials Plugin docs)
* enforce_quality_gate must be a boolean
Regex was tested using an online tool
A simple pipeline that used the Sonarqube Library's static_code_analysis step was run
> adding sonarqube library config

- docker/library_config.groovy
* Added a library config file for the Docker library
Added library_config.groovy
* Has two required fields: registry & cred
* registry can't start w/ "http" and can only contain certain characters (per Docker docs)
* cred can only contain certain characters (per Credentials Plugin docs)
* has two optional fields: build_strategy and repo_path_prefix
* build strategy is an enumerated type
* repo_path_prefix can only contain certain characters (per Docker docs)
Ran multiple pipelines with different combinations of settings in the pipeline config. The JTE version was built from the develop branch, so the future v1.2
> Docker library configuration

- openshift/library_config.groovy
Added a library config file for the Openshift library
Specified 6 optional fields in the library config file for the Openshift library:
* helm_configuration_repository must be a valid URL string
* helm_configuration_repository_credential must be a string with valid characters for a jenkins credential
* tiller_namespace must be a string with valid characters for a K8s label/namespace
* tiller_credential must be a string with valid characters for a jenkins credential
* url must be a valid URL string
* promote_previous_image must be a boolean
* image_repository_project must be a string with valid characters for a K8s label/namespace
All of these fields are optional because they have default values and/or can be replaced with values from an app_env
Unit tests still run
Successfully ran …
> Openshift library config

- owasp_dep_check/library_config.groovy
Added a library config for the Owasp Dependency Check library
Specified 5 optional fields in the library config file for the Owasp Dependency Check library:
* scan_target is a String
* exclude_dirs is a string (could be optimized to be a comma-separated list)
* cvss_threshold is either "pass" or a positive integer
* image_version is a valid Docker tag
* report_format is an enumerated type
Tested regex expressions w/ an online tester
> adding owasp_dep_check/library_config.groovy

- owasp_zap/library_config.groovy
Added a library config for the Owasp ZAP library
Specified two optional fields in the library config for the Owasp ZAP library:
* target must be a valid URL string
* vuln_threshold is an enumerated type
Tested the regex expression using an online tool
> Adding owasp_zap library config

- protractor/library_config.groovy
Added a library config file for the Protractor library
Specified 3 optional fields in the library config file for the Protractor library:
* url must be a valid URL string
* enforce must be a Boolean
* config_file must be a String
Tested regex expression through an online tool
> adding protractory library config

- sdp/library_config.groovy
Added a library config file for the SDP library
Added library_config.groovy
* Has two required fields: images.registry & images.cred
* images.registry _must_ start with http(s) and can only contain certain characters (per Docker docs)
* images.cred can only contain certain characters (per Credentials Plugin docs)
* Has two optional fields: images.repository * images.docker_args
* images.repository can only contain certain characters (per Docker docs)
* images.docker_args must be a String
Tested regex expressions w/ an online tool
Ran a simple pipeline that used the inside_sdp_image step (via the Openshift library's deploy_to step)
> Sdp library config

- github/library_config.groovy
Reverts boozallen/sdp-libraries#38
> Revert "GitHub library config"

- .style/_static/style.css
- .style/_static/theme_overrides.css
- .style/templates/layout.html
- conf.py
- index.rst
> refactor docs to be independently deployable

- README.rst
Fixing docs link in README.rst
Link now works
- [ x All new and existing tests passed.
> Update Docs link in README.rst

- .github/pull_request_template.md
- CONTRIBUTING.rst
- index.rst
* Adds CONTRIBUTING.rst, a contribution guide for this repository
* updates index.rst to include a link to the contribution guide in the navigation bar
* updates the PR template to include more relevant fields in the checklist
Deployed the docs locally (`make docs live`) and confirmed that the page formatting and hyperlinks were all correct
> Adding an SDP Libraries Contribution Guide

- docker/unit-tests/GetImagesToBuildSpec.groovy
> fixed broken docker tests

- sdp/inside_sdp_image.groovy
- sdp/unit-tests/InsideSdpImageSpec.groovy
CLOUDPLAT-642: removing body.resolveStrategy and body.delegate assignment
> fix/remove sdp lib delegate and resolveStrategy assignment

- docker/README.rst
- docker/build.groovy
- docker/retag.groovy
- docker/unit-tests/BuildSpec.groovy
- docker/unit-tests/RetagSpec.groovy
Added the option to specify if after building or retagging Docker image, the pipeline will remove the local image it built. 
If this option is not specified, the default is not to remove the local image. If the option is specified but is not a Boolean, an error will occur.
This branch was tested in an environment where we are building the docker image and deploying it. 
Cases tested:
remove_local_image not present -> do not remove local docker image
remove_local_image is present and set to true -> remove local docker image
remove_local_image is present and not boolean -> error thrown
remove_local_image is present and set to false -> do not remove local docker image
> Option to Remove Local Docker Image

- kubernetes/README.rst
- kubernetes/deploy_to.groovy
- kubernetes/ephemeral.groovy
Added SDP Kubernetes library to deploy workloads through the SDP pipeline into Kubernetes platforms
Added SDP Kubernetes library to deploy workloads through the SDP pipeline into Kubernetes platforms
This has been tested on an SDP platform hosted on generic Kubernetes with the deployment of a sample app (Devnation / Bahmoria) onto a generic Kubernetes platform
- [ x] Docs change / refactoring / dependency upgrade
- [ x] New feature (non-breaking change which adds functionality)
- [ x] I am submitting this pull request to the appropriate branch
- [ x] I have labeled this pull request appropriately
- [x ] I have updated the documentation accordingly.
> Added Kubernetes library

- aws/README.rst
Adding USCIS accts challenge aws sdp library to the experimental branch
> Aws uscis exp

- s3/README.rst
- s3/deploy_to.groovy
> feat: adding uscis-accts /s3 library

- docs/modules/ROOT/nav.adoc
fixing library typo in docs sidebar
Dependency Checker -> Dependency Check
N/A
> docs nav bar typo fix

- docs/modules/ROOT/pages/libraries/kubernetes.adoc
Added a dependency section to the kubernetes library.
> updated kubernetes page with library dependencies.

- docs/modules/ROOT/pages/libraries/kubernetes.adoc
- libraries/kubernetes/deploy_to.groovy
- libraries/kubernetes/ephemeral.groovy
> add config options to k8s library

- .gitignore
- docs/modules/ROOT/pages/index.adoc
- libraries/git/steps/git.groovy
Allowing for checkout support in github
Github support for checkout
Tested locally and in use currently for AIOPS project from forked branch.
> Checkout support

- build.gradle
- docs/antora.yml
Updated antora version to latest
> updated version to 'latest'

- .gitignore
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/libraries/maven.adoc
- libraries/maven/maven.groovy
- test/maven/MavenTestSpec.groovy
Adding support for Maven integration.
Added library for Maven that supports phases, goals, profiles, and properties. Requires Maven installed on Jenkins.
Tested on local Jenkins deployment using all parameters to build a Maven project.
Automated tests written and all existing and new tests pass.
> [AIOPS-32] Adding in support, tests, and documentation for Maven

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/libraries/npm.adoc
- docs/modules/ROOT/pages/unit_testing/executing-tests.adoc
- libraries/npm/steps/npm_build.groovy
- libraries/npm/steps/npm_invoke.groovy
- libraries/npm/steps/unit_test.groovy
- test/npm/NpmBuildSpec.groovy
- test/npm/NpmInvokeSpec.groovy
- test/npm/UnitTestSpec.groovy
Implementes https://github.com/boozallen/sdp-libraries/issues/134
Adds a npm library that runs npm commands in a specified version of nodeJs. All requirements outline in https://github.com/boozallen/sdp-libraries/issues/134 are fulfilled. In addition, `npm install` is an optional step before running the npm command, and the install can be one of several defined options.
Unit tests are included.
This library was developed and tested against a local Jenkins instance, using the nvm image described in https://github.com/boozallen/sdp-images/pull/32
> Npm Library

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/libraries/maven.adoc
- libraries/maven/steps/maven.groovy
- test/maven/MavenTestSpec.groovy
took code from #118 and create a 'main' branch PR
> Pr 118 main

- build.gradle
- libraries/docker/steps/get_images_to_build.groovy
Bumps the version to `3.2`.
N/A
> bump version to 3.2

- libraries/owasp_dep_check/README.md
- libraries/owasp_dep_check/steps/application_dependency_scan.groovy
- libraries/owasp_dep_check/test/ApplicationDependencySpec.groovy
Adds the ability to use a suppression file with the OWASP dependency scan for whitelisting vulnerabilities.
Tested in a Jenkins instance.
> Enable suppression file support in OWASP dependency scan

- libraries/dotnet/README.md
- libraries/dotnet/steps/dotnet_invoke.groovy
Updates the DotNet library to support overriding the DotNet SDK SDP image that is used.
Tested in a Jenkins instance.
> Support overriding the DotNet SDK SDP image used

- catalog-info.yaml
Adds a catalog-info.yaml file to add this repository as a component in the Developer Portal
> Add catalog-info.yaml file for use with the Developer Portal

- catalog-info.yaml
Merging catalog-info.yaml file added to develop to main branch
> Merging catalog-info.yaml file added to develop to main branch

- catalog-info.yaml
Remove internal documentation site from public GitHub repository
Updates the Backstage configuration file to remove internal BAH marketing site
Since this site is internal to the BAH network, we should remove this from the open sourced solution to reduce confusion and broken links.
> Update catalog-info.yaml to remove internal link

- catalog-info.yaml
Move change in catalog-info.yaml file from develop to main to update component in the Developer Portal
> Move catalog-info.yaml change from develop to main

- libraries/npm/README.md
- libraries/npm/steps/npm_invoke.groovy
Updated the NPM library to allow overriding the container image used.
Tested in a Jenkins pipeline.
> Update NPM library to allow overriding the container image used

- libraries/yarn/README.md
- libraries/yarn/steps/yarn_invoke.groovy
- libraries/yarn/test/YarnInvokeSpec.groovy
Implements a new Yarn library that works very similarly to the existing NPM library.
Tested in a Jenkins pipeline.
> Implement new Yarn library

- libraries/syft/README.md
- libraries/syft/library_config.groovy
- libraries/syft/steps/generate_sbom.groovy
- libraries/syft/test/GenerateSBOMSpec.groovy
Provides support to generate the other supported report formats. Allows multiple format types to be generated at a time.
Tested in pipeline and with Unit tests
> Syft multiple formats

- libraries/syft/README.md
- libraries/syft/library_config.groovy
- libraries/syft/steps/generate_sbom.groovy
- libraries/syft/test/GenerateSBOMSpec.groovy
Reverts boozallen/sdp-libraries#189
> Revert "Syft multiple formats"

- libraries/syft/README.md
- libraries/syft/library_config.groovy
- libraries/syft/steps/generate_sbom.groovy
- libraries/syft/test/GenerateSBOMSpec.groovy
This PR adds multiple output format capability for the Syft library. 
Added multi formats to Syft and updated unit tests.
Tested in a JTE Jenkins pipeline and with unit tests.
> Syft multiple SBOM formats

- libraries/syft/README.md
- libraries/syft/library_config.groovy
- libraries/syft/steps/generate_sbom.groovy
Adds ability to remove left over syft config yaml files 
Tested in jenkins pipeline
> Syft config removal option

- catalog-info.yaml
This PR updates the owner field for the Developer Portal catalog-info.yaml file
> Updated Developer Portal owner

- catalog-info.yaml
This PR updates the owner field for the Developer Portal catalog-info.yaml file
> Updated component owner for Backstage catalog-info.yaml

- catalog-info.yaml
This PR adds a system to the catalog-info.yaml file for the purpose of showing this Component under the correct System in the Developer Portal
> Added system to catalog info

- catalog-info.yaml
Added "reusable" tag to the `catalog-info.yaml` files so these component will show up when using the "Reusable" filter in Backstage.
N/A
> Added "reusable" tag to `catalog-info.yaml`

- catalog-info.yaml
Removed public visibility from catalog-info.yaml file. This will be handled in the booz-allen-software-studio tenant's publicEntities list
Draft PR until related changes are merged in
> Removed public visibility from component
