Makefile, UnitTestingDockerfile
Updated the makefile so someone can run `make test` to run the unit tests.
It's also possible to run `make test docker` to execute the unit tests w/ Docker to ensure a uniform execution environment. During the first run a new container image is built, and subsequent runs use that container image. This cuts back on the time spent downloading dependencies.
=> `Make test` Command

openshift/unit-tests/DeployToSpec.groovy
Fixing one of deploy_to's tests
The previous commit to sdp-libraries, which added the `--install` to the `helm upgrade` command being called in `deploy_to()`, broke some of the regex matchers in DeployToSpec.groovy. This commit updates those matchers to account for the change.
`make test` passed
=> updating DeployToSpec's tests

build.gradle, unit_test.Dockerfile
Two changes in this PR:
1. unit_test.Dockerfile no longer runs the downloadDependencies Gradle task. It seems that that task was removed from build.gradle, and the tests run fast enough that downloading the dependencies ahead of time is no longer as useful.
2. When running the "test" Gradle task, the resources are properly named. Before, the contents of the library folders, as opposed to the folders themselves were being copied into the test resources directory. This presents two problems: the unit tests expect a step's groovy file to be inside a library folder, and libraries that provide identically-named steps would cause collisions. Now, the entire library folder is copied into the test resources directory.
1) Dockerfile update
a) removed the existing sdp-library-testing image from my …
=> Unit test fixes

build.gradle, openshift/README.rst, openshift/deploy_to.groovy, openshift/unit-tests/DeployToSpec.groovy
Currently if the pipeline has detected and recorded a "FEATURE_SHA," i.e. the last code change was a "merge," then it will _always_ attempt to pull a previously-built image from a PR or previous commit and promote it. These changes allow users to make this promotion process optional for their entire pipeline, or select to not promote images for certain application environments. 
Added jenkins-spock unit tests to DeployToSpec.groovy. The tests ran as expected
=> Allow for optional image promotion on deploy_to after a merge

sdp/README.rst
Fixing a typo in "SDP" library docs, where the field "repo" should have been "repository" (Ref: inside_sdp_image.groovy:22)
=> fixing typo in "SDP" library docs

sdp/library_config.groovy
Fixing a typo in the sdp library's library_config.groovy file, where one of the regex expressions was not formatted to match `http://` or `https://` at the beginning of the value.
* Ran unit tests
* Tested regex expression w/ an [online checker](https://regexr.com/)
* Ran a simple pipeline using the updated library repo
=> Sdp libconfig fix

docker/get_images_to_build.groovy
Docker images cannot have uppercase letters in their names so if a repository has an uppercase letter, will receive the following error: flag: invalid reference format: repository name must be lowercase
Changed the get images docker step so the repo name will always be lower case.
This branch was tested in an environment where we are building the docker image and deploying it. After making the change, we were able to deploy repositories that have uppercase letters in them. We did not see any other effects with this change.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I am submitting this pull request to the appropriate branch
- [ x] I have labeled this pull request appropriately
- [ x] I have updated the documentation accordingly.
- [ x] All new and existing tests …
=> Docker lib

sonarqube/static_code_analysis.groovy
Bug fix to enable the enforce_quality_gate functionality of the SDP sonarqube library
The current check for `enforce_quality_gate` treats a value of `false` the same as if the parameter wasn't set at all. Since the default behavior is to set `enforce` to `true` (when `enforce_quality_gate` isn't set), there currently isn't a way to set `enforce` to `false`.
1. Cloned the boozallen/sdp-libraries repo to local GitLab instance
2. Updated local copy of sdp-libraries/sonarqube/static_code_analysis.groovy with change committed here, as well as copious `println` statements to track variable values throughout stage
3. Pointed a Jenkins job to the local sdp-libraries repo and reran the static_code_analysis stage
4. Confirmed both `config.enforce_quality_gate` and `enforce` were set to false during …
=> update enforce_quality_gate check to handle boolean false

docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/libraries/sdp.adoc, libraries/sdp/archive_pipeline_config.groovy, libraries/sdp/create_workspace_stash.groovy
Updates the `sdp` library so that the SDP Pipeline Libraries can support JTE 1.7. 
[JTE 1.7](https://github.com/jenkinsci/templating-engine-plugin/releases/tag/1.7) removed checking out a repository to create a "workspace" stash and archiving the aggregated pipeline configuration as a build artifact from its initialization process. 
This PR adds that functionality to the `sdp` library.
=> add steps to SDP library to support JTE 1.7

libraries/github/github_enterprise_constructor.groovy, libraries/github_enterprise/github_enterprise_constructor.groovy, libraries/gitlab/gitlab_constructor.groovy
JTE 1.7 changed the Lifecycle hook parameter type from a generic Map to a specific HookContext. 
Recommendation is to use Groovy Ducktyping and simply not specify the context param type. 
Removed Map type from context param
=> remove Type Map from github init step context parameters

README.adoc
Updating readme link to documentation
Current link (https://boozallen.github.io/sdp-docs/sdp-libraries/latest/index.html) returns `Page Not Found`
Tested current and updated link in Chrome and Safari.
=> fix link to documentation

docs/modules/ROOT/pages/libraries/google_lighthouse.adoc
This PR edits the Lighthouse library documentation to make it clear that builds will fail if a score is less than or equal to the defined failure threshold. The existing documentation reads "less than this" but the [code for failure checking](https://github.com/boozallen/sdp-libraries/blob/master/libraries/google_lighthouse/accessibility_compliance_scan.groovy#L90) uses `<=` and not `<`.
=> Edit Lighthouse failure threshold docs for clarity.

libraries/google_lighthouse/accessibility_compliance_scan.groovy
Edge case where if the fail or warn thresholds were set to 0, the default would be used.
This was caused by 0 evaluating to **false** in the elvis operator expression. 
validated with mock inputs in the groovy console
- [] I have updated the documentation accordingly.
=> Allow Google Lighthouse Thresholds to be set to 0

docs/modules/ROOT/pages/libraries/sonarqube.adoc, libraries/sonarqube/library_config.groovy, libraries/sonarqube/static_code_analysis.groovy
Refactoring of the SonarQube library to remove hard coded conventions and enhance configurability.
Previously, the `sonarqube` library would hard code via cli parameters the values of `sonar.projectKey` and `sonar.projectName`.  The default values for these parameters required that a source code library was being used to populate `REPO_NAME` and `BRANCH_NAME` environment variables. 
These have been removed. 
You will need to set the value of `sonar.projectKey` and `sonar.projectName` via **either** a `sonar-project.properties` file at the root of the current working directory when `static_code_analysis()` is invoked: 
```
sonar.projectKey=myCoolProject:${env.BRANCH_NAME}
sonar.projectName=My Cool Project: ${env.BRANCH_NAME}
```
**or** by setting these values in …
=> refactor sonarqube library

.gitignore, docs/modules/ROOT/pages/libraries/sdp.adoc, libraries/git/steps/git_distributions.groovy, libraries/sdp/steps/getStep.groovy, libraries/sdp/steps/jteVersion.groovy, test/JTEPipelineSpecification.groovy
* Patches the `git` library's call to `getBinding().getStep()` which disappeared in JTE 2.1
* adds a `jteVersion` step which supports logical operations for working around the current JTE version
* adds a `getStep` utility in the sdp libraries since all that logic shouldn't be in the `git` library
=> patch `git` library to support JTE 2.1 in a backwards compatible way

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/libraries/docker_compose.adoc, libraries/docker_compose/steps/compose.groovy, test/docker_compose/DockerComposeSpec.groovy
Adding in library support for Docker Compose.
Added library for Docker Compose that supports up and down commands with multiple files, environment variables, and the ability to pause the pipeline for some amount of time to ensure the containers have had time to deploy before continuing.
Tested on local Jenkins deployment using all parameters to deploy containers, execute integration tests against those containers, and tear down when done.
Automated tests written and all existing and new tests pass.
=> Docker compose support

docs/modules/ROOT/pages/libraries/anchore.adoc, libraries/anchore/library_config.groovy, libraries/anchore/steps/add_registry_creds.groovy, libraries/kubernetes/steps/deploy_to.groovy
Adds method `add_registry_creds` in Anchore library. This method will add to Anchore private docker registry credentials, allowing Anchore to pull and scan images from this repository.
This PR also changes the `git push` to `git "push"` in the `deploy_to` step of the Kubernetes library. This is done because 'push' of `git push` no longer appears to be found.
Adding an optional `add_registry_creds` step in the Anchore library, with additional optional configuration items: 
```
docker_registry_credential_id = String
docker_registry_name = String
k8s_credential = String
k8s_context = String
```
These changes are opt-in, being fully reverse compatible with Anchore library usage prior to the commit.
This PR also includes updates to the Anchore documentation page.
This new method has been …
=> adding add_registry_creds for anchore

libraries/git/steps/on_change.groovy
The SDP docs say `on_change` is "a combination of on_commit and on_merge". This PR makes this true.
The code for `on_commit` has the following check:
```groovy
// do nothing if not commit
if (!env.GIT_BUILD_CAUSE.equals("commit")) 
return
```
The code for `on_merge` has the following check:
```groovy
// do nothing if not merge
if (!env.GIT_BUILD_CAUSE.equals("merge"))
return
```
`on_pull_request` checks for `"pr"` which makes sense for running pipeline steps for a PR.
`on_change` was checking for `"commit"` or `"pr"`, but this didn't make much sense to me because "change" implies a change has happened, not that is might happen (from an open PR).
It seems much more useful for `on_change` to be a Git Flow helper method triggered from either a normal commit or a merge commit (after a PR is …
=> Make on_change a combination of on_commit and on_merge 

libraries/docker/README.md, libraries/docker/steps/get_images_to_build.groovy, libraries/docker/test/GetImagesToBuildSpec.groovy
Closes #84 
Adding `image_name` to Docker library parameters (will continue to default to `env.REPO_NAME`)
Added new test to `GetImagesToBuildSpec.groovy` (`image_name Properly Overrides env.REPO_NAME When Set`) and ran all tests locally
=> Adding configurable image_name to Docker

.vale.ini, docs/concepts/unit-testing/faq.md, libraries/git/README.md, libraries/kubernetes/README.md, libraries/npm/README.md, libraries/openshift/README.md, mkdocs.yml, resources/docs/Dockerfile
Updating [docs theme](https://github.com/squidfunk/mkdocs-material/) to latest.
* Updated container image used for docs to latest: [8.0.4](https://hub.docker.com/layers/squidfunk/mkdocs-material/8.0.4/images/sha256-25cd187896afa72c61f7a35e0225cef8a7dca2241070564b86d89d5b734c27c7?context=explore)
* Swapped out manual footnotes in code blocks with new [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations)
* Updated FAQs page to use [collapsible code admonition blocks](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#removing-the-title)
Locally using `just lint-docs` and `just serve` to review
=> [Documentation]: updating docs theme and applying new theme features

libraries/owasp_dep_check/README.md
Fixing incorrect example config
`scan_target` should be `scan`
N/A
=> fixing typo in example config snippet

libraries/maven/steps/maven_invoke.groovy
Fixing broken required field check.
`containsKey` check not working on `env` array directly--moving to checking combined configs (`envVars`) array instead.
Locally
=> fixing Maven required field check

libraries/maven/steps/maven_invoke.groovy
Fixing broken Maven config array handling
Attempting to use `env` for array library config variables doesn't work--replacing with internal step arrays
In a local environment
=> fixing Maven config array handling

libraries/syft/steps/generate_sbom.groovy, libraries/syft/test/GenerateSBOMSpec.groovy
Address file path issue when generating SBOMs using the Syft library for containers in repositories with multi-tiered directory structures.
Updated filenames used for container tarballs to replace `/` with `-` to keep all archives at the top level and avoid directory permission/availability issues.
=> fixing Syft library file path issue

libraries/syft/steps/generate_sbom.groovy, libraries/syft/test/GenerateSBOMSpec.groovy
Bugfix for Syft SBOM results filepath.
Missed a spot where additional `/` could slip into the output filename, causing permissions and access errors later in the step.
=> Syft filepath fix

libraries/syft/steps/generate_sbom.groovy, libraries/syft/test/GenerateSBOMSpec.groovy
Fixing incorrect use of syft's `output` parameter to correctly dump SBOM to a file that can be archived in Jenkins.
Local behavior doesn't match documentation or behavior within the library. Run locally, `syft my_container -o json=my_results.json` is writing SBOM contents to `my_results.json`, despite the fact that that file should be a json template definition, not the output target.
Fix just switches the `=` to an ` > `
=> Syft command fix

libraries/grype/README.md, libraries/grype/library_config.groovy, libraries/grype/steps/container_image_scan.groovy
Adds "None" severity.
The "None" severity allows CVE severity checking to be turned off.
In BASS pipeline
=> Add "none"  option to disable fail on severity for Grype scans

libraries/grype/README.md, libraries/grype/resources/transform-grype-scan-results.sh, libraries/grype/steps/container_image_scan.groovy, libraries/grype/test/ContainerImageScanSpec.groovy, libraries/syft/steps/generate_sbom.groovy
Add Grype ability to scan an SBOM file Also fixes bug from BASS-1328
adds logic to locate an acceptable SBOM artifact for scanning when sbom_scan equals true, otherwise grype scans the image from the container registry. Also changes the grype commands output redirection from >> to > to fix duplicate CVEs causing the transform script to error out.
In a JTE Jenkins pipeline and with Unit tests
=> Grype SBOM scan capability

libraries/cypress/steps/end_to_end_test.groovy
Bugfixing Cypress subdirectory check
When using a separate test repo, it is checked out into a new subdirectory: `test_repo_dir`
Configured Cypress tests need to be run from that subdirectory, requiring a variable check and `dir() {`, as needed
Locally
=> Cypress test repo subdirectory fix

libraries/cypress/steps/end_to_end_test.groovy
Bugfix: missed one subdirectory reference
Updated configured `report_path` variable in cases where an external test repo is set (and cloned into a newly-created subdirectory)
Local and in-house dev environments
=> Additional Cypress subdirectory fix

libraries/owasp_dep_check/README.md, libraries/owasp_dep_check/steps/application_dependency_scan.groovy
Getting rid of `latest` default image tag in the OWASP Dependency Check library step.
While the library step image could be overridden, the default value, `latest` could introduce breaking changes without warning. Have updated the step to use the current stable image tag from our GitHub packages registry: `7.3.0-8.6-2`
Locally
=> OWASP Dep Check: change default image tag from 'latest'

libraries/docker/README.md, libraries/docker/steps/build.groovy, libraries/docker/steps/get_images_to_build.groovy, libraries/docker/test/BuildSpec.groovy, libraries/docker/test/GetImagesToBuildSpec.groovy
Added a new Docker build strategy called `dockerfiles` to support multiple Dockerfiles and/or Dockerfiles with custom file names (i.e. `Dockerfile.backend`, `Dockerfile.frontend`, etc.).
This supports the monorepo use-case where files needed to be shared between different Docker images.
Tested in a Jenkins pipeline using the following config:
```groovy
libraries {
docker {
registry = '<redacted>'
cred = 'repo-creds'
image_name = 'my-project'
build_strategy = 'dockerfiles'
dockerfiles {
backend {
context = '.'
dockerfile = 'Dockerfile.backend'
}
frontend {
context = '.'
dockerfile = 'Dockerfile.frontend'
}
}
}
}
```
=> Added a new Docker build strategy to support multiple Dockerfiles and Dockerfiles with custom file names

libraries/yarn/README.md, libraries/yarn/steps/yarn_invoke.groovy, libraries/yarn/test/YarnInvokeSpec.groovy
Adds an `immutable` option to the yarn library `yarnInstall` configuration field
This adds the `immutable` option to `yarnInstall` to support Yarn 3 users. `frozen-lockfile` was the way to do this in previous Yarn versions. This no longer exists in Yarn 3 and was replaced with the `immutable` flag.
=> Add immutable option to yarn install

libraries/npm/README.md, libraries/npm/steps/npm_invoke.groovy, libraries/npm/test/NpmInvokeSpec.groovy
Adds the option to define a `git{}` config under a custom step defined in the NPM library. The `git` block requires three parameters that set the repo (`url`), branch (`branch`), and Jenkins stored credential ID (`cred`) to pull a repository down and run the NPM script defined within that context. Useful, for example, if end-to-end test code is stored in a separate repository from your main codebase.
Locally, and with additional unit tests
=> Add separate git repo option to NPM library
